# Pull base image
FROM python:3.7

# don't write .pyc files
ENV PYTHONDONTWRITEBYTECODE 1
# don't buffer output
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /django-pgpubsub

#Install dependencies
COPY Pipfile Pipfile.lock /django-pgpubsub/
RUN pip install pipenv && pipenv install --system

# Copy project
# Keeping COPY Pipfile Pipfile.lock /django-pgpubsub/ separately
# from the below means the docker doesn't need to repeat that
# step whenever we make a code change (docker only runs parts of file,
# from top down, which haven't changed since last run).
COPY . /django-pgpubsub/
