FROM python:3.9

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /django-pgpubsub

COPY Pipfile Pipfile.lock /django-pgpubsub/
RUN pip install --upgrade pip
RUN pip install pipenv && pipenv install --system
COPY . /django-pgpubsub/
