# Generated by Django 3.2.18 on 2023-05-16 06:05

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgpubsub', '0003_notification_db_version'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='notification',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_notification_set_db_version', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    NEW.db_version := (\n                        SELECT max(id)\n                        FROM django_migrations\n                        WHERE app = ((NEW.payload #>> '{}')::jsonb ->> 'app')\n                    );\n                    RETURN NEW;\n                ", hash='39db2d905a9216a1fc1697d1f5c4f0600e3f6b39', operation='INSERT OR UPDATE', pgid='pgtrigger_pgpubsub_notification_set_db_version_ac4cd', table='pgpubsub_notification', when='BEFORE')),
        ),
    ]
