# Generated by Django 4.1 on 2023-04-08 03:00

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_author_user'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='pgpubsub_72091',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_72091', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload TEXT;', func="\n            \n            payload := json_build_object(\n                'app', 'tests',\n                'model', 'Post',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES ('pgpubsub_72091', to_json(payload::text));\n        \n            perform pg_notify('pgpubsub_72091', payload);\n            RETURN NEW;\n        ", hash='6826a7b3b62b051b84afffbc2bd7801742474c5e', operation='INSERT', pgid='pgtrigger_pgpubsub_72091_67aeb', table='tests_post', when='AFTER')),
        ),
    ]
