# Generated by Django 4.1 on 2023-04-11 03:33

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_post_pgpubsub_72091_post_pgpubsub_72091'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='pgpubsub_72091',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_72091', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload TEXT;', func="\n            \n            payload := json_build_object(\n                'app', 'tests',\n                'model', 'Post',\n                'old', row_to_json(OLD),\n                'new', row_to_json(NEW)\n              );\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES ('pgpubsub_72091', to_json(payload::text));\n        \n            perform pg_notify('pgpubsub_72091', payload);\n            RETURN NEW;\n        ", hash='16a6a1629e6a9fe42f73d460319a92689efdcbfe', operation='DELETE', pgid='pgtrigger_pgpubsub_72091_67aeb', table='tests_post', when='AFTER')),
        ),
    ]
