# Generated by Django 4.1 on 2023-04-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_remove_post_pgpubsub_72091_post_pgpubsub_72091'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='alternative_name',
            field=models.TextField(db_column='other', null=True),
        ),
    ]
