# Generated by Django 3.2.12 on 2023-11-15 13:37

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_payload_stores_proper_jsonb'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='pgpubsub_160cf',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='child',
            name='pgpubsub_89ef9',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='childofabstract',
            name='pgpubsub_b1c0b',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='pgpubsub_a83de',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='pgpubsub_72091',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_160cf', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; get_payload_extras_func TEXT; extras JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Author"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.get_payload_extras_func\', True)\n                INTO get_payload_extras_func;\n            IF get_payload_extras_func IS NOT NULL THEN\n                EXECUTE \'SELECT \' || quote_ident(get_payload_extras_func) || \'()\'\n                    INTO extras;\n                payload := jsonb_insert(payload, \'{extras}\', extras);\n            END IF;\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_160cf\', payload);\n        \n            perform pg_notify(\'pgpubsub_160cf\', payload::text);\n            RETURN NEW;\n        ', hash='9492b9c4235c977beaea77ccd016ee81e51444f7', operation='INSERT', pgid='pgtrigger_pgpubsub_160cf_72a36', table='tests_author', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='child',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_89ef9', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; get_payload_extras_func TEXT; extras JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Child"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.get_payload_extras_func\', True)\n                INTO get_payload_extras_func;\n            IF get_payload_extras_func IS NOT NULL THEN\n                EXECUTE \'SELECT \' || quote_ident(get_payload_extras_func) || \'()\'\n                    INTO extras;\n                payload := jsonb_insert(payload, \'{extras}\', extras);\n            END IF;\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_89ef9\', payload);\n        \n            perform pg_notify(\'pgpubsub_89ef9\', payload::text);\n            RETURN NEW;\n        ', hash='aa9a46a1ee682b78b093d817df9dc267f3545ba0', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_89ef9_92bc1', table='tests_child', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='childofabstract',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_b1c0b', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; get_payload_extras_func TEXT; extras JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "ChildOfAbstract"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.get_payload_extras_func\', True)\n                INTO get_payload_extras_func;\n            IF get_payload_extras_func IS NOT NULL THEN\n                EXECUTE \'SELECT \' || quote_ident(get_payload_extras_func) || \'()\'\n                    INTO extras;\n                payload := jsonb_insert(payload, \'{extras}\', extras);\n            END IF;\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_b1c0b\', payload);\n        \n            perform pg_notify(\'pgpubsub_b1c0b\', payload::text);\n            RETURN NEW;\n        ', hash='5450deaa8b49599d7d78cc8f32ddfa81553882cc', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_b1c0b_c8531', table='tests_childofabstract', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_a83de', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; get_payload_extras_func TEXT; extras JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Media"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.get_payload_extras_func\', True)\n                INTO get_payload_extras_func;\n            IF get_payload_extras_func IS NOT NULL THEN\n                EXECUTE \'SELECT \' || quote_ident(get_payload_extras_func) || \'()\'\n                    INTO extras;\n                payload := jsonb_insert(payload, \'{extras}\', extras);\n            END IF;\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_a83de\', payload);\n        \n            perform pg_notify(\'pgpubsub_a83de\', payload::text);\n            RETURN NEW;\n        ', hash='710bc37c522b4b09187ef6926ced675e1aa23222', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_a83de_cacbb', table='tests_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_72091', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; get_payload_extras_func TEXT; extras JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Post"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.get_payload_extras_func\', True)\n                INTO get_payload_extras_func;\n            IF get_payload_extras_func IS NOT NULL THEN\n                EXECUTE \'SELECT \' || quote_ident(get_payload_extras_func) || \'()\'\n                    INTO extras;\n                payload := jsonb_insert(payload, \'{extras}\', extras);\n            END IF;\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_72091\', payload);\n        \n            perform pg_notify(\'pgpubsub_72091\', payload::text);\n            RETURN NEW;\n        ', hash='36a4ee090402180ff69073f5fd6aa9fd5d88d56a', operation='DELETE', pgid='pgtrigger_pgpubsub_72091_67aeb', table='tests_post', when='AFTER')),
        ),
    ]
