# Generated by Django 3.2.12 on 2023-11-16 13:00

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_payload_stores_proper_jsonb'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='pgpubsub_160cf',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='child',
            name='pgpubsub_89ef9',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='childofabstract',
            name='pgpubsub_b1c0b',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='pgpubsub_a83de',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='pgpubsub_72091',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_160cf', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Author"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT COALESCE(current_setting(\'pgpubsub.notification_context\', True), \'{}\')::jsonb\n                INTO notification_context;\n            payload := jsonb_insert(payload, \'{context}\', notification_context);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_160cf\', payload);\n        \n            perform pg_notify(\'pgpubsub_160cf\', payload::text);\n            RETURN NEW;\n        ', hash='0c70137e92883450adaa16bcb45de73e23b82fb4', operation='INSERT', pgid='pgtrigger_pgpubsub_160cf_72a36', table='tests_author', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='child',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_89ef9', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Child"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT COALESCE(current_setting(\'pgpubsub.notification_context\', True), \'{}\')::jsonb\n                INTO notification_context;\n            payload := jsonb_insert(payload, \'{context}\', notification_context);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_89ef9\', payload);\n        \n            perform pg_notify(\'pgpubsub_89ef9\', payload::text);\n            RETURN NEW;\n        ', hash='cf798ce24042b3016c4aaba8a644bdc707b13371', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_89ef9_92bc1', table='tests_child', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='childofabstract',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_b1c0b', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "ChildOfAbstract"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT COALESCE(current_setting(\'pgpubsub.notification_context\', True), \'{}\')::jsonb\n                INTO notification_context;\n            payload := jsonb_insert(payload, \'{context}\', notification_context);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_b1c0b\', payload);\n        \n            perform pg_notify(\'pgpubsub_b1c0b\', payload::text);\n            RETURN NEW;\n        ', hash='d4ab1811b7c894c483fc6d5269db7e49ce51158a', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_b1c0b_c8531', table='tests_childofabstract', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_a83de', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Media"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT COALESCE(current_setting(\'pgpubsub.notification_context\', True), \'{}\')::jsonb\n                INTO notification_context;\n            payload := jsonb_insert(payload, \'{context}\', notification_context);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_a83de\', payload);\n        \n            perform pg_notify(\'pgpubsub_a83de\', payload::text);\n            RETURN NEW;\n        ', hash='4a793ae41f14dbe46316ff95f0517dab16653ce5', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_a83de_cacbb', table='tests_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_72091', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE payload JSONB; notification_context JSONB;', func='\n            \n            payload := \'{"app": "tests", "model": "Post"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT COALESCE(current_setting(\'pgpubsub.notification_context\', True), \'{}\')::jsonb\n                INTO notification_context;\n            payload := jsonb_insert(payload, \'{context}\', notification_context);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_72091\', payload);\n        \n            perform pg_notify(\'pgpubsub_72091\', payload::text);\n            RETURN NEW;\n        ', hash='f9c2be3e92c93fd272970de09dc7e94e5ddd02a6', operation='DELETE', pgid='pgtrigger_pgpubsub_72091_67aeb', table='tests_post', when='AFTER')),
        ),
    ]
