# Generated by Django 3.2.12 on 2024-02-16 11:37

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_payload_context'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='author',
            name='pgpubsub_160cf',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='child',
            name='pgpubsub_89ef9',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='childofabstract',
            name='pgpubsub_b1c0b',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='media',
            name='pgpubsub_a83de',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='post',
            name='pgpubsub_72091',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='author',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_160cf', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE notify_payload TEXT; payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "tests", "model": "Author"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_160cf\', payload)\n            RETURNING id::text INTO notify_payload;\n        \n            perform pg_notify(\'pgpubsub_160cf\', notify_payload);\n            RETURN NEW;\n        ', hash='5059766458d9cc08bdc82542d6c73b99bc19c98b', operation='INSERT', pgid='pgtrigger_pgpubsub_160cf_72a36', table='tests_author', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='child',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_89ef9', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE notify_payload TEXT; payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "tests", "model": "Child"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_89ef9\', payload)\n            RETURNING id::text INTO notify_payload;\n        \n            perform pg_notify(\'pgpubsub_89ef9\', notify_payload);\n            RETURN NEW;\n        ', hash='5ef4245b21803f43b5470ef807fc61a9beb8e6e3', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_89ef9_92bc1', table='tests_child', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='childofabstract',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_b1c0b', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE notify_payload TEXT; payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "tests", "model": "ChildOfAbstract"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_b1c0b\', payload)\n            RETURNING id::text INTO notify_payload;\n        \n            perform pg_notify(\'pgpubsub_b1c0b\', notify_payload);\n            RETURN NEW;\n        ', hash='70e23b76598e1697643f8a473d77ba6e04f4c20a', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_b1c0b_c8531', table='tests_childofabstract', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='media',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_a83de', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE notify_payload TEXT; payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "tests", "model": "Media"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_a83de\', payload)\n            RETURNING id::text INTO notify_payload;\n        \n            perform pg_notify(\'pgpubsub_a83de\', notify_payload);\n            RETURN NEW;\n        ', hash='8b7e1505347519e2f80c35e9da6fa5da7c133ee2', operation='UPDATE OR INSERT', pgid='pgtrigger_pgpubsub_a83de_cacbb', table='tests_media', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='post',
            trigger=pgtrigger.compiler.Trigger(name='pgpubsub_72091', sql=pgtrigger.compiler.UpsertTriggerSql(declare='DECLARE notify_payload TEXT; payload JSONB; notification_context_text TEXT;', func='\n            \n            payload := \'{"app": "tests", "model": "Post"}\'::jsonb;\n            payload := jsonb_insert(payload, \'{old}\', COALESCE(to_jsonb(OLD), \'null\'));\n            payload := jsonb_insert(payload, \'{new}\', COALESCE(to_jsonb(NEW), \'null\'));\n            SELECT current_setting(\'pgpubsub.notification_context\', True) INTO notification_context_text;\n            IF COALESCE(notification_context_text, \'\') = \'\' THEN\n                notification_context_text := \'{}\';\n            END IF;\n            payload := jsonb_insert(payload, \'{context}\', notification_context_text::jsonb);\n        \n            \n            INSERT INTO pgpubsub_notification (channel, payload)\n            VALUES (\'pgpubsub_72091\', payload)\n            RETURNING id::text INTO notify_payload;\n        \n            perform pg_notify(\'pgpubsub_72091\', notify_payload);\n            RETURN NEW;\n        ', hash='c6e87030e2953f454dadd7d4f0b2fcb9de3d9ccb', operation='DELETE', pgid='pgtrigger_pgpubsub_72091_67aeb', table='tests_post', when='AFTER')),
        ),
    ]
